function mex_all()

files = { ...
'ekfmex.c' ...
'dynamic_matrix_mex.c' ...
'propagate_mex.c' ...
'vicon_update_mex.c' ...
'ekf_imu_mex.c' ...
'calcQ_mex.c' ...
'cholinv_mex.c' ...
};

for i=1:length(files)
    mexcompile(files{i});
end

end

function mexcompile(fname)
	mex('-I../../crazyflie-firmware/src/modules/interface', '-I../../crazyflie-firmware/src/modules/src', fname);
end
