name: Crazyswarm System Python CI

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-16.04
            pyVer: python

          - os: ubuntu-18.04
            pyVer: python

          - os: ubuntu-20.04
            pyVer: python3

    runs-on: ${{ matrix.os }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt install -y swig lib${{ matrix.pyVer }}-dev ${{ matrix.pyVer }}-numpy ${{ matrix.pyVer }}-yaml ${{ matrix.pyVer }}-matplotlib ${{ matrix.pyVer }}-pytest ${{ matrix.pyVer }}-scipy

    - name: Build
      run: |
        CSW_PYTHON=${{ matrix.pyVer }} ./buildSimOnly.sh 

    - name: Test
      run: |
        cd ros_ws/src/crazyswarm/scripts
        ${{ matrix.pyVer }} -m pytest
